#!/bin/bash
logtime=`date -r /var/log/secure +%Y%m%d%H%M%S`
systime=`date +%Y%m%d%H%M%S`
display=`date -r /var/log/secure`
result=$(($systime - $logtime))

if [ $result -gt 6000 ]; then
echo "2 SecureLog - Critical - Last log created at $display"
exit 2
elif [ $result -gt 4500 ]; then
echo "1 SecureLog - Warning - Last log created at $display"
exit 1
else echo "0 SecureLog - OK - Last log created at $display" 
exit 0
fi
