#!/usr/bin/bash
if [ "$1" = "" ]
then
echo "Usage: ./check_log logfile"
else 
	logtime=`date -r $1 +%Y%m%d%H%M%S`
	systime=`date +%Y%m%d%H%M%S`
	display=`date -r $1`
	result=$((($systime-$logtime)/100))
	case $result in
		[0-44]*)
		echo "Last log created in $display"
		exit 0
		;;
		[45-59]*)
		echo "Last log created in $display"
		exit 1
		;;
		[60-9999999999]*)
		echo "Last log created in $display"
		exit 2
		;;
	esac
fi